### PR TITLE
Enable interpretation of backslash escapes

### PR DESCRIPTION
**Pull request by a-st**
This enables interpretation of backslash escapes, otherwise '\n' appears in the bash script

### CODE REVIEW

**Comment by ryecoaaron** [comment]
I use this plugin a lot and don't have \n in my files.  Plus, I am currently porting this plugin to OMV 5.x which will not use echo anymore since OMV 5.x uses saltstack for configuration.

**Comment by a-st** [comment]
Alright, for me it was surely reproducible that the generated /var/lib/openmediavault/cron.d/rsnapshot file always contained a messed up shebang and some control characters (\n). Maybe this is just a OMV 4.x issue and it only takes effect if you run the script from cli (e.g. sudo /var/lib/openmediavault/cron.d/rsnapshot daily)

**Comment by ryecoaaron** [comment]
I only use it on OMV 4.x on at least five systems.  Did you install OMV with the OMV iso?  What locale is your system?

**Comment by a-st** [comment]
```
admin@NAS542:~$ locale
LANG=de_DE.UTF-8
LANGUAGE=de
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES=de_DE.UTF-8
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by a-st** [comment]
The installation is running on Debian Stretch

**Comment by ryecoaaron** [comment]
I would guess the different locale is potentially causing this.  if the c.utf-8 locale isn't available, there might issues as well.

You mention it is stretch.  Is there a desktop environment installed?

**Comment by a-st** [comment]
Might be, therefor I submitted my pull request 😉 There is no desktop environment installed/running

**Comment by ryecoaaron** [comment]
I understand this fixes your system but most people aren't reporting that this is broken.  So, I need to make sure this doesn't break other systems.  I just haven't had a chance to do this.

**Comment by a-st** [comment]
I really get your point. An issue also only occurs if you run the generated rsnapshot through a CLI. If the script is invoked through OMV/Cron, it works flawlessly.

**Pull request closed without merging**
